account_balance: 640.0841
account_margin: 0.02
active_direction: ''
active_order: false
ask: 1.11763
bid: 1.11755
commission: 5.0e-05
last_transaction: 0
last_transaction_id: '17451'
margin_available: 777.1841
margin_used: 0.0
oanda_account: 101-001-7518331-001
oanda_api: f3e81960f4aa75e7e3da1f670df51fae-73d8ac6fb611eb976731c859e2517a9b
open_positions: 0
pair: EUR_USD
pair_margin: 0.02
pips: 3.25
pips_step: 0.25
realized: 0
trade_risk: 0.01
